version: 0.2

#env:
  #variables:
  # key: "value"
  # key: "value"
  #parameter-store:
  # key: "value"
# key: "value"

phases:
  install:
    commands:
      #- add-apt-repository ppa:ubuntu-toolchain-r/test
      #- apt-get update
      #- apt-get install gcc-7 -y
      #- gcc --version
      #- update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
      - gcc --version

  pre_build:
    commands:
      - mvn -B clean compile

  build:
    commands:
      - mvn -B test jacoco:report
      - "awk -F, \"{ instructions += $4 + $5; covered += $5 } END { print 100*covered/instructions }\" target/site/jacoco/jacoco.csv > coverage.txt"
      - cat coverage.txt
  #post_build:
  #commands:
  # - command
  # - command
#artifacts:
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths